name: app_planeta
description: |
  App de gerenciamento de planetas no estilo CRUD.
  Criado para o projeto TalentoTech - PR.

  ğŸŒ Adicione, edite e remova planetas facilmente.
  ğŸš€ Feito em Flutter com SQLite para armazenamento.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.4.1
  path: ^1.9.0
  google_fonts: ^6.1.0
  animated_text_kit: ^4.2.3
  gsform: ^0.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logos/talento_tech_logo.png
    - assets/logos/talento_tech_text.png
    - assets/images/A_cosmic_background_with_stars_and_nebulae_in_spac.png

